---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cartservice
  namespace: frothly-store
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frothly-store
        name: cartservice
        role: cartservice
        tier: middleware
    spec:
      containers:
        - name: cartservice
          image: k8tan/cart_microservice
          imagePullPolicy: Always
          ports:
            - name: cartservice
              containerPort: 4201
