apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # Namespace not needed for cluster role
  # namespace: frothly-store
  name: frothly-read-only-role
rules:
- apiGroups: [""]
  #
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "secrets"
  resources: ["secrets", "services"]
  verbs: ["get", "watch", "list"]
