apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: frothly-default-read-only
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: frothly-read-only-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: frothly-store
