---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: productservice 
  namespace: frothly-store
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frothly-store
        name: productservice
        role: productservice
        tier: middleware 
    spec:
      containers:
        - name: productservice
          image: k8tan/product_microservice
          imagePullPolicy: Always
          ports:
            - name: productservice
              containerPort: 6767
