---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: productdb
  labels:
    name: productdb
  namespace: frothly-store
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frothly-store
        name: productdb
        role: mysql
        tier: db
    spec:
      containers:
        - name: productdb
          #image: k8tan/product_db
          image: k8tan/product_db:latest
          imagePullPolicy: Always
          ports:
            - name: mysql
              containerPort: 3306
